// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openbao/openbao/sdk/v2/logical (interfaces: SystemView,Storage)
//
// Generated by this command:
//
//	mockgen -package gcp -destination auth/gcp/mocks_test.go github.com/openbao/openbao/sdk/v2/logical SystemView,Storage
//

// Package gcp is a generated GoMock package.
package gcp

import (
	context "context"
	reflect "reflect"
	time "time"

	consts "github.com/openbao/openbao/sdk/v2/helper/consts"
	pluginutil "github.com/openbao/openbao/sdk/v2/helper/pluginutil"
	wrapping "github.com/openbao/openbao/sdk/v2/helper/wrapping"
	logical "github.com/openbao/openbao/sdk/v2/logical"
	gomock "go.uber.org/mock/gomock"
)

// MockSystemView is a mock of SystemView interface.
type MockSystemView struct {
	ctrl     *gomock.Controller
	recorder *MockSystemViewMockRecorder
	isgomock struct{}
}

// MockSystemViewMockRecorder is the mock recorder for MockSystemView.
type MockSystemViewMockRecorder struct {
	mock *MockSystemView
}

// NewMockSystemView creates a new mock instance.
func NewMockSystemView(ctrl *gomock.Controller) *MockSystemView {
	mock := &MockSystemView{ctrl: ctrl}
	mock.recorder = &MockSystemViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemView) EXPECT() *MockSystemViewMockRecorder {
	return m.recorder
}

// CachingDisabled mocks base method.
func (m *MockSystemView) CachingDisabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CachingDisabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CachingDisabled indicates an expected call of CachingDisabled.
func (mr *MockSystemViewMockRecorder) CachingDisabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CachingDisabled", reflect.TypeOf((*MockSystemView)(nil).CachingDisabled))
}

// ClusterID mocks base method.
func (m *MockSystemView) ClusterID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterID indicates an expected call of ClusterID.
func (mr *MockSystemViewMockRecorder) ClusterID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterID", reflect.TypeOf((*MockSystemView)(nil).ClusterID), ctx)
}

// DefaultLeaseTTL mocks base method.
func (m *MockSystemView) DefaultLeaseTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultLeaseTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// DefaultLeaseTTL indicates an expected call of DefaultLeaseTTL.
func (mr *MockSystemViewMockRecorder) DefaultLeaseTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultLeaseTTL", reflect.TypeOf((*MockSystemView)(nil).DefaultLeaseTTL))
}

// EntityInfo mocks base method.
func (m *MockSystemView) EntityInfo(entityID string) (*logical.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EntityInfo", entityID)
	ret0, _ := ret[0].(*logical.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EntityInfo indicates an expected call of EntityInfo.
func (mr *MockSystemViewMockRecorder) EntityInfo(entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EntityInfo", reflect.TypeOf((*MockSystemView)(nil).EntityInfo), entityID)
}

// GeneratePasswordFromPolicy mocks base method.
func (m *MockSystemView) GeneratePasswordFromPolicy(ctx context.Context, policyName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePasswordFromPolicy", ctx, policyName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePasswordFromPolicy indicates an expected call of GeneratePasswordFromPolicy.
func (mr *MockSystemViewMockRecorder) GeneratePasswordFromPolicy(ctx, policyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePasswordFromPolicy", reflect.TypeOf((*MockSystemView)(nil).GeneratePasswordFromPolicy), ctx, policyName)
}

// GroupsForEntity mocks base method.
func (m *MockSystemView) GroupsForEntity(entityID string) ([]*logical.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupsForEntity", entityID)
	ret0, _ := ret[0].([]*logical.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupsForEntity indicates an expected call of GroupsForEntity.
func (mr *MockSystemViewMockRecorder) GroupsForEntity(entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupsForEntity", reflect.TypeOf((*MockSystemView)(nil).GroupsForEntity), entityID)
}

// ListVersionedPlugins mocks base method.
func (m *MockSystemView) ListVersionedPlugins(ctx context.Context, pluginType consts.PluginType) ([]pluginutil.VersionedPlugin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVersionedPlugins", ctx, pluginType)
	ret0, _ := ret[0].([]pluginutil.VersionedPlugin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVersionedPlugins indicates an expected call of ListVersionedPlugins.
func (mr *MockSystemViewMockRecorder) ListVersionedPlugins(ctx, pluginType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVersionedPlugins", reflect.TypeOf((*MockSystemView)(nil).ListVersionedPlugins), ctx, pluginType)
}

// LocalMount mocks base method.
func (m *MockSystemView) LocalMount() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocalMount")
	ret0, _ := ret[0].(bool)
	return ret0
}

// LocalMount indicates an expected call of LocalMount.
func (mr *MockSystemViewMockRecorder) LocalMount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalMount", reflect.TypeOf((*MockSystemView)(nil).LocalMount))
}

// LookupPlugin mocks base method.
func (m *MockSystemView) LookupPlugin(ctx context.Context, pluginName string, pluginType consts.PluginType) (*pluginutil.PluginRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupPlugin", ctx, pluginName, pluginType)
	ret0, _ := ret[0].(*pluginutil.PluginRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupPlugin indicates an expected call of LookupPlugin.
func (mr *MockSystemViewMockRecorder) LookupPlugin(ctx, pluginName, pluginType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupPlugin", reflect.TypeOf((*MockSystemView)(nil).LookupPlugin), ctx, pluginName, pluginType)
}

// LookupPluginVersion mocks base method.
func (m *MockSystemView) LookupPluginVersion(ctx context.Context, pluginName string, pluginType consts.PluginType, version string) (*pluginutil.PluginRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupPluginVersion", ctx, pluginName, pluginType, version)
	ret0, _ := ret[0].(*pluginutil.PluginRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupPluginVersion indicates an expected call of LookupPluginVersion.
func (mr *MockSystemViewMockRecorder) LookupPluginVersion(ctx, pluginName, pluginType, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupPluginVersion", reflect.TypeOf((*MockSystemView)(nil).LookupPluginVersion), ctx, pluginName, pluginType, version)
}

// MaxLeaseTTL mocks base method.
func (m *MockSystemView) MaxLeaseTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxLeaseTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// MaxLeaseTTL indicates an expected call of MaxLeaseTTL.
func (mr *MockSystemViewMockRecorder) MaxLeaseTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxLeaseTTL", reflect.TypeOf((*MockSystemView)(nil).MaxLeaseTTL))
}

// MlockEnabled mocks base method.
func (m *MockSystemView) MlockEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MlockEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// MlockEnabled indicates an expected call of MlockEnabled.
func (mr *MockSystemViewMockRecorder) MlockEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MlockEnabled", reflect.TypeOf((*MockSystemView)(nil).MlockEnabled))
}

// NewPluginClient mocks base method.
func (m *MockSystemView) NewPluginClient(ctx context.Context, config pluginutil.PluginClientConfig) (pluginutil.PluginClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPluginClient", ctx, config)
	ret0, _ := ret[0].(pluginutil.PluginClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewPluginClient indicates an expected call of NewPluginClient.
func (mr *MockSystemViewMockRecorder) NewPluginClient(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPluginClient", reflect.TypeOf((*MockSystemView)(nil).NewPluginClient), ctx, config)
}

// PluginEnv mocks base method.
func (m *MockSystemView) PluginEnv(arg0 context.Context) (*logical.PluginEnvironment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PluginEnv", arg0)
	ret0, _ := ret[0].(*logical.PluginEnvironment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PluginEnv indicates an expected call of PluginEnv.
func (mr *MockSystemViewMockRecorder) PluginEnv(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PluginEnv", reflect.TypeOf((*MockSystemView)(nil).PluginEnv), arg0)
}

// ReplicationState mocks base method.
func (m *MockSystemView) ReplicationState() consts.ReplicationState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicationState")
	ret0, _ := ret[0].(consts.ReplicationState)
	return ret0
}

// ReplicationState indicates an expected call of ReplicationState.
func (mr *MockSystemViewMockRecorder) ReplicationState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicationState", reflect.TypeOf((*MockSystemView)(nil).ReplicationState))
}

// ResponseWrapData mocks base method.
func (m *MockSystemView) ResponseWrapData(ctx context.Context, data map[string]any, ttl time.Duration, jwt bool) (*wrapping.ResponseWrapInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponseWrapData", ctx, data, ttl, jwt)
	ret0, _ := ret[0].(*wrapping.ResponseWrapInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResponseWrapData indicates an expected call of ResponseWrapData.
func (mr *MockSystemViewMockRecorder) ResponseWrapData(ctx, data, ttl, jwt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponseWrapData", reflect.TypeOf((*MockSystemView)(nil).ResponseWrapData), ctx, data, ttl, jwt)
}

// Tainted mocks base method.
func (m *MockSystemView) Tainted() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tainted")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Tainted indicates an expected call of Tainted.
func (mr *MockSystemViewMockRecorder) Tainted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tainted", reflect.TypeOf((*MockSystemView)(nil).Tainted))
}

// VaultVersion mocks base method.
func (m *MockSystemView) VaultVersion(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VaultVersion", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VaultVersion indicates an expected call of VaultVersion.
func (mr *MockSystemViewMockRecorder) VaultVersion(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VaultVersion", reflect.TypeOf((*MockSystemView)(nil).VaultVersion), arg0)
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStorage) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorage)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockStorage) Get(arg0 context.Context, arg1 string) (*logical.StorageEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*logical.StorageEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorage)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockStorage) List(arg0 context.Context, arg1 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStorageMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStorage)(nil).List), arg0, arg1)
}

// ListPage mocks base method.
func (m *MockStorage) ListPage(arg0 context.Context, arg1, arg2 string, arg3 int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPage", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPage indicates an expected call of ListPage.
func (mr *MockStorageMockRecorder) ListPage(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPage", reflect.TypeOf((*MockStorage)(nil).ListPage), arg0, arg1, arg2, arg3)
}

// Put mocks base method.
func (m *MockStorage) Put(arg0 context.Context, arg1 *logical.StorageEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockStorageMockRecorder) Put(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockStorage)(nil).Put), arg0, arg1)
}
